version: '3'

services:
  falcbot:
    command: python falcbot/falcbot.py
    build: .
    container_name: "slackbot"
    ports:
      - 80:80
    volumes:
      - type: bind
        source: $HOME/.OpenEye/
        target: /home/mambauser/.OpenEye/
    env_file:
      - .env